### ISSUE TITLE
405 : Method not allowed

### ISSUE THREAD

**Issue by madcoda9000** [eusonlito/Password-Manager#14]
Hello,

i've followed your installation guide. But when i open the startpage i get the following error:

405 :  Method Not Allowed

![chrome_zG3PX7sUP5](https://user-images.githubusercontent.com/25504739/164413672-bd7f6762-2fb5-4226-be96-93315ed49c68.png)

In the log folder ist no file created, so i don't know how to see any logfile?

I hope you can help here.

Additional Info: when i enter the url including index.php, it's working. But my url is looking like that: https://mydomain.com/passmgr/index.php/user/profile (for ex.).

I am sure that is not the way it shoul be...

Additional Infos: I've enable debug mode and regenrated the cache. Now i can provide the following infomations:

![chrome_UVHqk0UKUp](https://user-images.githubusercontent.com/25504739/164425402-47d694db-e13f-46d2-ab9f-310d84b067b3.png)

Best whishes
Sascha

**Comment by eusonlito** [comment]
Laravel have some problems with projects not installed on root path.

Try to delete `bootstrap/cache/routes-v7.php` file.

**Comment by madcoda9000** [comment]
Hello,

that did the trick! Many thanks for that hint.

Best wishes
Sascha
