### ISSUE TITLE
Microsoft Authenticator

### ISSUE THREAD

**Issue by madcoda9000** [eusonlito/Password-Manager#15]
Hello,

it would be great if 2fa is possbile with Microsoft authenticator app. I've tried that already but it seems not to work.

Best Wishes
Sascha

**Comment by madcoda9000** [comment]
I don' know that. But I tried to use the Microsoft Authenticator app for configuring 2fa. And the generated codes semms not to work.

**Comment by eusonlito** [comment]
Let me try 😊

**Comment by eusonlito** [comment]
Yes, it's working :)

**Comment by eusonlito** [comment]
Closing :)
