### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by madcoda9000** [eusonlito/Password-Manager#16]
Hello,

if you want, i can offer to do the german translations for you. Just tell me what to do.

Best Wishes
Sascha

**Comment by eusonlito** [comment]
Oh, great!

You can copy english folder from `resources/lang/en` to `resources/lang/de` and translate the files contents.

To test it, you can change the `config/app.php` file:

```
    'locale' => env('APP_LOCALE', 'es'),
    'locales' => ['es', 'en'],
    'locale_system' => ['es' => 'es_ES.UTF-8', 'en' => 'en_US.UTF-8'],
    'fallback_locale' => 'es',
```
to

```
    'locale' => env('APP_LOCALE', 'de'),
    'locales' => ['es', 'en', 'de'],
    'locale_system' => ['es' => 'es_ES.UTF-8', 'en' => 'en_US.UTF-8', 'de' => 'de_DE.UTF-8'],
    'fallback_locale' => 'es',
```

As `config` is cached, you should delete the file `bootstrap/cache/config.php`.

Thanks!

**Comment by madcoda9000** [comment]
ok, i'll try that

**Comment by madcoda9000** [comment]
Whooha, i was not aware that there is so much to translate. This could take a few days, but i'm on the run :-)

**Comment by madcoda9000** [comment]
I was able to trasnlate it faster than i thought. Attached you'll find a zip file with the translated files.

Best Wishes
Sascha

[de.zip](https://github.com/eusonlito/Password-Manager/files/8531209/de.zip)
