### ISSUE TITLE
imposible usar 2FA

### ISSUE THREAD

**Issue by elnarvi** [eusonlito/Password-Manager#19]
buenas

desde hace unos días no puedo conectar usando 2FA, me dice siempre que el código es incorrecto

he tenido que acceder a la base de datos y desactivarlo por query:

update user set tfa_enabled = '0' where id = 1;

ha estado funcionado bien durante meses, y desde hace unos días no funciona

alguna explicación?

**Comment by eusonlito** [comment]
Hola! qué raro. No se ha tocado nada de autenticación desde hace bastante tiempo, sólo actualización de dependencias.

Cúando has actualizado la plataforma?
Si la borras de la aplicación de Google Authenticator y la vuelves a añadir funciona?

Yo acabo de probarlo ahora mismo sin cambiar nada y sin problema.

Saludos!

**Comment by elnarvi** [comment]
no había actualizado la plataforma desde hace meses, de hecho he probado a actualizarla esta mañana por si era algún bug y el problema persiste

si, he probado a borrarlo de la aplicación de Google Authenticator y persiste

voy a crear otro usuario distinto y lo pruebo, por descartar cosas

**Comment by eusonlito** [comment]
Pues es rarísimo que así de primeras deje de funcionar.

Es posible que hayas cambiado el nombre de la aplicación (APP_NAME) en el fichero `.env`? O el email que usas en la aplicación?

**Comment by elnarvi** [comment]
![2fa](https://user-images.githubusercontent.com/26577209/172128158-549ccaa7-c846-4a28-b16e-e302a154774e.png)

no, no lo he cambiado, ni el nombre de la aplicación ni el e-mail

lo único "especial" que tengo configurado es un puerto distinto del 80 o 443, concretamente el 8080, sin entorno seguro

pero vamos que así estaba configurado desde hace meses y no daba ningún problema

voy a probar a reiniciar la máquina

**Comment by eusonlito** [comment]
No tienes ningún error en `storage/logs/laravel-XXXX.log`?

Prueba a habilitar el debug `APP_DEBUG=true` en el fichero `.env` (recuerda realizar un `composer deploy` para garantizar la compatibilidad de código/datos).

**Comment by elnarvi** [comment]
al reiniciar la máquina vuelve a funcionar... en fin, solucionado

**Comment by eusonlito** [comment]
A saber... que raro :stuck_out_tongue:
