### ISSUE TITLE
php artisan migrate problem

### ISSUE THREAD

**Issue by banaantje** [eusonlito/Password-Manager#2]
Hello, 

Currently trying to install password manager on a fresh ubuntu installation. I am now having a problem with the 'php artisan migrate' command:

In Connection.php line 703:

  SQLSTATE[HY000] [1045] Access denied for user 'dbuser'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = <databasename> and table_name = migrations and table_type = 'BASE TABLE')

The SQL command is using the database name in the table_schema section. 
Also, it looks like the database is still empty (i do not know if that should have happened already)

Many thanks for your help!

**Comment by eusonlito** [comment]
You should check the `DB_XXX` credentials in `.env` file. Maybe you should change the `DB_SOCKET=/var/run/mysqld/mysqld.sock` with `DB_HOST=localhost` and `DB_PORT=3306`.

**Comment by banaantje** [comment]
Sorry, that did not fix it for me. At first... In the end it was fixed. I've done a few things but nothing worked out until I read on the internet that I need to clear the cache:

php artisan config:clear

After that I was able to successfully run the 'php partisan migrate' command.
Case closed.

**Comment by eusonlito** [comment]
Yes, `composer install` command include chache generation. After any `.env` or `config/*.php` change you need to regenerate it with calling again the commad `composer install --no-dev`. Regards!
