### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tunavis** [eusonlito/Password-Manager#20]
Good day.

Can you please make a video of the installation or atleast explain how  to import the database?

**Comment by eusonlito** [comment]
Hi! You have all installation instructions here https://github.com/eusonlito/Password-Manager#installation

**Comment by tunavis** [comment]
I did see this but where is the location of the sql db? sorry im new to laravel.

**Comment by tunavis** [comment]
Thanks eusonlito. Tell me where does the connection string happen which file to I specify the connection to my DB?

**Comment by eusonlito** [comment]
Follow the installation steps :)

Environment (url, database, etc...) configuration the point 4 https://github.com/eusonlito/Password-Manager#installation

**Comment by tunavis** [comment]
Sorry for being a handful.. I'm getting the following error when running the composer:   In Filesystem.php line 187:

  /home/gito/Password-Manager/vendor does not exist and could not be created.


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

**Comment by eusonlito** [comment]
Is because you are executing the composer command in a folder (`/home/gito/Password-Manager`) without write permissions for this user. The folder should have the the same user as the user who is running the composer command.

**Comment by tunavis** [comment]
Fantastic, should the repository be cloned in /var/www/*** location?

**Comment by eusonlito** [comment]
It's not about the project location, it's about the user that download the code and execute all commands, must be the same.

**Comment by eusonlito** [comment]
This step is cron job setup, you should put these line inside the user cron with command: `sudo crontab -e -u SAME_USER_AS_PROJECT_OWNER`

**Comment by tunavis** [comment]
Ok i've done everything, now if i try to access the password manager I get the following: 
![image](https://user-images.githubusercontent.com/8057000/174740880-c3d57a15-35ef-4019-8647-cac20e85c902.png)

**Comment by eusonlito** [comment]
Do you have configured your Apache server with PHP support and the correct virtualhost?

**Comment by tunavis** [comment]
All php and extensions has been installed. Please see attached as well as the virtual host file

![image](https://user-images.githubusercontent.com/8057000/174795637-d066e38f-423b-4488-8052-3f6f3cdcdbbc.png)

**Comment by eusonlito** [comment]
Do you have `mod_rewrite` enabled and `AllowOverride All`?

**Comment by tunavis** [comment]
Once I enabled AllowOverride all my apache service won't start

**Comment by eusonlito** [comment]
Then you should check your apache error logs :)

Check some post about how to configure apache with php/laravel support https://docs.boltcms.io/5.0/howto/making-sure-htaccess-works

**Comment by tunavis** [comment]
Hi Eusolito,

Would it be possible to assist me with the installation? I've tried everything if you could please assist me via anydesk i will really appreciate it. I've reinstalled php+ extention, mysql and apache. Project has been composed as well.
