### ISSUE TITLE
Extra's

### ISSUE THREAD

**Issue by tunavis** [eusonlito/Password-Manager#22]
Good Day,

Is it possible to explain me how to add logo to login page? 

As well as to add extra type applications?

**Comment by eusonlito** [comment]
Login page uses this template: https://github.com/eusonlito/Password-Manager/blob/master/resources/views/domains/user/auth-credentials.blade.php

To create a custom type:

1. Add the type here: https://github.com/eusonlito/Password-Manager/blob/master/app/Domains/App/Service/Type/Type.php
2. Use some Format class as base from here https://github.com/eusonlito/Password-Manager/blob/master/app/Domains/App/Service/Type/Format
3. Duplicate some type folder with the new format type https://github.com/eusonlito/Password-Manager/blob/master/resources/views/domains/app/create.blade.php
4. Add the image icon inside https://github.com/eusonlito/Password-Manager/blob/master/resources/views/assets/images/

**Comment by tunavis** [comment]
After adding and making relevant changes Im getting a internal 500 error on the applications tab.

**Comment by eusonlito** [comment]
You can enable debug mode on `.env` file with `APP_DEBUG=true` (and `composer deploy` after the change).

**Comment by tunavis** [comment]
Receiving following issue: 

![image](https://user-images.githubusercontent.com/8057000/182335049-512df47c-0d8e-40e9-a989-95ba6062adae.png)

**Comment by tunavis** [comment]
Seems like some s
[App.zip](https://github.com/eusonlito/Password-Manager/files/9240698/App.zip)
ort of 
[en.zip](https://github.com/eusonlito/Password-Manager/files/9240700/en.zip)
email class is missing
[email.zip](https://github.com/eusonlito/Password-Manager/files/9240675/email.zip)
.

**Comment by tunavis** [comment]
Let me know if there is something i'm missing. Thank you for your time.

**Comment by eusonlito** [comment]
You can create a public repository with your changes, then I will can compare sources. What's your new format?

**Comment by tunavis** [comment]
I very new to the laraval environment. I only want 2 extra type of applications.

1. Email - In put field should only have a username(the user email) and Password(User email password)
2. idrive - Input field for username, password and Encryption key field)

**Comment by tunavis** [comment]
I would really appreciate it if you could assist me with this. I love the look and feel of your application and what to put time in to understand the laravel framework. But I need this passwordmanager asap running.

**Comment by eusonlito** [comment]
Please, create a public repository from this and I can help you with the changes.

**Comment by tunavis** [comment]
[Type.zip](https://github.com/eusonlito/Password-Manager/files/9281103/Type.zip)


Attached is the type folder with the new changes. Please amend these in the software.

**Comment by eusonlito** [comment]
Please @tunavis, create a public fork of this repository and I will can help you. I can't work with zip because it is very difficult to track the changes.

**Comment by tunavis** [comment]
Like I mentioned I’m very new to laravel hardly know how it  works. If you could please just explain in more depth how to achieve this. Sorry for the inconvenience

**Comment by eusonlito** [comment]
Hi! I can see your fork https://github.com/tunavis/Password-Manager

I will try to work today to help you.

Regards!

**Comment by tunavis** [comment]
Hi Thank you for the update I see changes are made but at soon as I select idrive type i get the following error
![geg](https://user-images.githubusercontent.com/8057000/184639504-5b4bf43a-fe79-4f17-bc02-b1490b664e68.png)
.

**Comment by tunavis** [comment]
Same issue with Email type.

**Comment by tunavis** [comment]
?

**Comment by eusonlito** [comment]
You have a new PR in your repository.
