### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by tunavis** [eusonlito/Password-Manager#28]
Hi Eusonlito,

Thank you first of all for all your assistance so far. I'm trying to run this on https using nginx proxy manager. As soon I enable the proxy route from http to https I'm getting CSS/JS issues. Can someone assist in this regard.

Screenshot below:

![image](https://user-images.githubusercontent.com/8057000/187657530-e20b0a85-20b4-4b94-ad63-649e285c7121.png)

**Comment by eusonlito** [comment]
Is the request URL correct? Have you configured the `APP_URL` with the public URL?

**Comment by h3nr1-g** [comment]
hey @tunavis ,
I had the same issue a couple of days ago. The problem is that Laravel uses HTTP for the generation of the asset URLs. I created the pull request https://github.com/eusonlito/Password-Manager/pull/31, where I added the enforcement of HTTPS in case we running the application in production mode and the application URL starts with "https".

**Comment by tunavis** [comment]
Hi @h3nr1-g 

Thank you for the change but my page won't load after changed applied.

**Comment by eusonlito** [comment]
I have added the `ASSET_URL` variable to `config/app.php`, then you can define your own `ASSET_URL` inside your custom `.env` file.

**Comment by tunavis** [comment]
So should the ASSET_URL have your https URL?

**Comment by eusonlito** [comment]
Yes, is the absolute base url `https://domain.com`.

**Comment by tunavis** [comment]
@h3nr1-g I'm having the issues regarding changes that @eusonlito made for the https. Does not work for my reverse proxy manager.

@h3nr1-g is possible to send me your reverse proxy setup for https to work.

**Comment by eusonlito** [comment]
@tunavis ASSET_URL doesn't work?

**Comment by tunavis** [comment]
@eusonlito not for me.

![image](https://user-images.githubusercontent.com/8057000/188901549-bd6360f0-9493-4008-9555-be925d37ccd1.png)

**Comment by eusonlito** [comment]
Is a different problem related with headers size (cookies). You can update the apache limit with `LimitRequestFieldSize 200000` or change the session driver to `file` or `redis`.

**Comment by h3nr1-g** [comment]
hey @tunavis , 
for the execution of the password manager application I'm using a docker-compose setup similar to one from PR https://github.com/eusonlito/Password-Manager/pull/23 . I'm also using nginx as a reverse proxy. Here is how my configuration for this virtual host looks like:

`server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name passwordmanager.foobar.com;
    
    # Enforce https
    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    }
    ssl_certificate "/etc/letsencrypt/live/passwordmanager.foobar.com/fullchain.pem";
    ssl_certificate_key "/etc/letsencrypt/live/passwordmanager.foobar.com/privkey.pem";


    location / {
        proxy_set_header    Host                         $http_host;
        proxy_set_header    X-Real-IP                 $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header    X-Frame-Options     SAMEORIGIN;

        proxy_pass		http://localhost:8001;
     }
}
`

**Comment by tunavis** [comment]
Sigh guys I'm just not getting this to work. lol.

@h3nr1-g thanks for the docker image, will try it out I would like to get the manual installation to work with my Reverse Proxy. Got it working for a second login went well until I added a Type. After that going back to the applications tab I got a Error 500 (Blue page).

**Comment by eusonlito** [comment]
@tunavis check the `storage/logs/laravel` folder.

**Comment by tunavis** [comment]
Attached is the log file
[laravel-2022-09-09.log](https://github.com/eusonlito/Password-Manager/files/9534453/laravel-2022-09-09.log)
![image](https://user-images.githubusercontent.com/8057000/189326305-787e26d9-4285-416e-82e8-e96f09dad132.png)

**Comment by tunavis** [comment]
And this happens as soon as I submit a Password Submission.(type)

**Comment by eusonlito** [comment]
Has the folder `public/storage` write permissions to web server user?

**Comment by tunavis** [comment]
!
![image](https://user-images.githubusercontent.com/8057000/189339855-334b338b-73b4-4fc6-b3d3-2e179405e3aa.png)

**Comment by tunavis** [comment]
I am the point if you can make a anydesk connection and assist I will appreciate it.

**Comment by tunavis** [comment]
Ok got it working changing the user and group to www-data of Password-Manager folder. 

But get the following error when I delete a password field.

![image](https://user-images.githubusercontent.com/8057000/189351173-32661aa3-1d56-4e04-9b19-a01403d7c386.png)

**Comment by tunavis** [comment]
Got it working changing the access of user and group to www-data. But experiencing issues when I delete as password field.
![image](https://user-images.githubusercontent.com/8057000/189351665-4e4e2c12-f468-4e3a-a76e-455ae65ee1fd.png)

**Comment by h3nr1-g** [comment]
hey @tunavis, 
sounds like the form will be submitted via plain HTTP. 

- Did you set the APP_URL to **https**://XXXXX ?
- Did you run `composer artisan-cache` ? Maybe some environment variables are not updated correctly.
- Is it possible to see your Apache virtual host config?

**Comment by tunavis** [comment]
Hi Gents,

Please see attached configs.
![Screenshot 2022-09-12 082948](https://user-images.githubusercontent.com/8057000/189588406-c5885fb3-8693-4916-83ca-a10525e21795.png)  - .env

![Screenshot 2022-09-12 083103](https://user-images.githubusercontent.com/8057000/189588470-f46dcab7-9119-4217-9756-14eca1bf74b7.png) - Virtual host apache

![Screenshot 2022-09-12 083236](https://user-images.githubusercontent.com/8057000/189588518-9c54317a-0559-4f3f-b570-de7a45ac3a35.png) - proxy manager 


![Screenshot 2022-09-12 083350](https://user-images.githubusercontent.com/8057000/189588562-224e8efa-0587-4e40-add6-1e2aaddee87d.png) - proxy manager certs


![image](https://user-images.githubusercontent.com/8057000/189588650-6aca0a2e-8205-4163-999c-14aba017f2cf.png) - app.php file

**Comment by tunavis** [comment]
![image](https://user-images.githubusercontent.com/8057000/189589267-29301094-854e-42e2-a5c4-83e59ff26db6.png)

**Comment by tunavis** [comment]
Reinstalled and configured permissions same issue.

![image](https://user-images.githubusercontent.com/8057000/189639396-a3e4ed59-2782-4a88-a367-aa51049cb81f.png)

**Comment by h3nr1-g** [comment]
Hey @tunavis , your Apache config Looks a little Bit Strange to me. Is there a reason why your virtual Host ist serving the App via plain HTTP? Maybe you could configure the virtual Host to serve the via HTTPS as well and remove the separate proxy

**Comment by tunavis** [comment]
Hi Guys. Sorry was on holiday. The problem is I need to use our reverse proxy manager(Reverse proxy manager) as this is our entry point.

**Comment by tunavis** [comment]
I dont see the reason for setting up certificates on my server itself using letsencrypt with certbot. If im already using a reverse proxy that does this for me

**Comment by h3nr1-g** [comment]
It was Just an Idea for Testing purposes to See If the application works or the issue is somehow related to Reverse Proxy config

**Comment by tunavis** [comment]
Will fo the change tomorrow for testing purposes thanks @h3nr1-g . I came across this documentation is this needed for the issue im experiencing?

![9A484E83-28B9-44A7-B041-C3EED6F2410C](https://user-images.githubusercontent.com/8057000/191585282-fb74b0ed-f22d-472b-b132-f0dd0c1bc5a6.jpeg)

**Comment by tunavis** [comment]
Yes, that is all that can make sense to me is that my load balancer that handles my HTTP and HTTPS is hosted on a different host. (This handles my certificates as well) Your Nginx reverse proxy is handling the hosting of your laravel app as well? and the vhost is on your side only listening on https?

**Comment by eusonlito** [comment]
Hello @tunavis, maybe this generic question about https and revese proxy can be solved in StackOverflow? You can paste here the final solution, but these issues must be directly related to this project :)

**Comment by tunavis** [comment]
> server_name passwordmanager.foobar.com;

Hi @h3nr1-g can you maybe share your apache vhost file?

**Comment by h3nr1-g** [comment]
Hey @tunavis , 
as described above, I'm using a nginx server as a Reverse Proxy.
