### ISSUE TITLE
'http://vault.domain.com/user/auth' not found

### ISSUE THREAD

**Issue by wangee** [eusonlito/Password-Manager#36]
Hello,

I strictly followed the install guide, and after browsing to 'http://vault.domain.com/user/auth', I got an error 404 "Not Found"

I tried installing Password-Manager on Debian 11 and Alma 9 and same behaviour happens.

.env file
`
APP_NAME="Password Manager"
APP_ENV=production
APP_KEY=base64:SOME_KEY
APP_DEBUG=false
APP_URL=http://localhost

APP_LOCALE=en

ASSET_URL=http://localhost

DEBUGBAR_ENABLED=false

AUTH_CHECK_ALLOWED=4
AUTH_CHECK_TIME=60
AUTH_LOCK_TIME=60
AUTH_TFA_ENABLED=true
AUTH_CERTIFICATE_ENABLED=true
AUTH_API_SECRET_ENABLED=true

AUTH_COUNTRY_ENABLED=false
AUTH_COUNTRY_ALLOWED=
AUTH_COUNTRY_IP_WHITELIST=127.0.0.1

LOG_CHANNEL=stack
LOG_REQUEST=false
LOG_DATABASE=false
LOG_MAIL=true
LOG_CURL=false
LOG_DAYS=30

DB_CONNECTION=mysql
DB_SOCKET=/var/lib/mysql/mysql.sock
DB_DATABASE=passwordmanager
DB_USERNAME=passwordmanager
DB_PASSWORD=some_password
DB_LOG=false

MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"
MAIL_CONTACT_ADDRESS=

CACHE_ENABLED=true
CACHE_DRIVER=file
CACHE_PREFIX=password-manager-cache-
CACHE_VERSION=1
CACHE_TTL=3600

SESSION_DRIVER=cookie
SESSION_LIFETIME=45000
SESSION_COOKIE=password-manager
SESSION_ENCRYPT=false

SENTRY_DSN=
SENTRY_TRACES_SAMPLE_RATE=0.0
`

apache.conf file
`ServerRoot "/etc/httpd"
Listen 80
Include conf.modules.d/*.conf
User apache
Group apache
ServerAdmin root@localhost
DocumentRoot "/home/Password-Manager/public"
<Directory "/home/Password-Manager/public">
    AllowOverride None
    Require all granted
</Directory>
<Directory "/home/Password-Manager/public">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
<IfModule dir_module>
    DirectoryIndex index.html
</IfModule>
<Files ".ht*">
    Require all denied
</Files>
ErrorLog "logs/error_log"
LogLevel warn
<IfModule log_config_module>
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common
    <IfModule logio_module>
      # You need to enable mod_logio.c to use %I and %O
      LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
    </IfModule>
    CustomLog "logs/access_log" combined
</IfModule>
<IfModule alias_module>
    ScriptAlias /cgi-bin/ "/var/www/cgi-bin/"
</IfModule>
<Directory "/var/www/cgi-bin">
    AllowOverride None
    Options None
    Require all granted
</Directory>
<IfModule mime_module>
    TypesConfig /etc/mime.types
    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz
    AddType text/html .shtml
    AddOutputFilter INCLUDES .shtml
</IfModule>
AddDefaultCharset UTF-8
<IfModule mime_magic_module>
    MIMEMagicFile conf/magic
</IfModule>
EnableSendfile on
IncludeOptional conf.d/*.conf
`

Any help would be appreciated.

**Comment by eusonlito** [comment]
Do you have the Apache2 `mod_rewrite` enabled?

**Comment by eusonlito** [comment]
The `AllowOverride None` option should be `AllowOverride All`.

**Comment by eusonlito** [comment]
Do you have defined the same `Directory` directive multiple times.

**Comment by wangee** [comment]
Yes, just found out Directory was defined twice :-D

I disabled mod_rewrite and now I got complains about .htaccess
`
[Wed Oct 19 12:18:13.818060 2022] [core:alert] [pid 3538:tid 3712] [client 10.0.251.3:58786] /home/Password-Manager/public/.htaccess: Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration
[Wed Oct 19 12:18:13.978423 2022] [core:alert] [pid 3538:tid 3714] [client 10.0.251.3:58798] /home/Password-Manager/public/.htaccess: Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration, referer: http://vault.domain.com/
`

.htaccess file 
`<IfModule mod_negotiation.c>
    Options -MultiViews -Indexes
</IfModule>

Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Methods "GET,PUT,POST,DELETE,PATCH,OPTIONS"
Header set Access-Control-Allow-Headers "Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Type, Origin, User-Agent, X-Requested-With"
Header set Access-Control-Allow-Credentials "true"
Header set Access-Control-Expose-Headers "Content-Disposition"
Header set Access-Control-Max-Age "86400"

RewriteEngine On

# Disable OPTIONS requests into framework
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule .* empty.html [NC,L]

# Handle Authorization Header
RewriteCond %{HTTP:Authorization} .
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

# Redirect Trailing Slashes If Not A Folder...
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} (.+)/$
RewriteRule ^ %1 [L,R=301]

# Handle Front Controller...
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]
`

**Comment by eusonlito** [comment]
You need to enable `mod_rewrite`.

As log say: `Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration`

**Comment by wangee** [comment]
I tried both.  

If I enable mod_rewrite, I got an Error 500 "Error del Sistema" but nothing reported in apache error log (error logging is set as warn)

**Comment by eusonlito** [comment]
Check laravel log inside the folder `storage/logs/`. Also you can enable the project debug with `APP_DEBUG=true`.

After change any `.env` file you need to refresh cache with `php artisan optimize`.

**Comment by wangee** [comment]
I ran  "php artisan optimize" and now I got a login screen.
I suggest you mention it in the install guide.

Thanks for the help.

I'm planning on participating to your project by doing the French translation. ;-)

**Comment by eusonlito** [comment]
The step 6 `composer artisan-cache` do the same as `php artisan optimize`.
