### ISSUE TITLE
2FA code is not getting generated

### ISSUE THREAD

**Issue by arvindjkhr** [eusonlito/Password-Manager#37]
2FA Code is not showing in my application 

![image](https://user-images.githubusercontent.com/39983369/196739762-63db08b3-9da6-4e45-a992-2838cc0d779a.png)

**Comment by eusonlito** [comment]
Check the image path on HTML. Any error on `storage/logs/laravel-XXXX.log` files?

**Comment by guillermazo** [comment]
Hi, I have the same problem

**Comment by arvindjkhr** [comment]
Please install php-gd and php-imagick extensions. And you should be goood
to go.

Thanks
Arvind
