### ISSUE TITLE
Attaching files to any App type.

### ISSUE THREAD

**Issue by eusonlito** [eusonlito/Password-Manager#44]
Suggesting another greeatly missing feature :  Attaching files to any App type.

_Originally posted by @wangee in https://github.com/eusonlito/Password-Manager/discussions/39#discussioncomment-4244161_

**Comment by eusonlito** [comment]
Hello @wangee, test the last release:

```bash
git pull && composer deploy
```

**Comment by wangee** [comment]
Thanks for the very fast response :-)
I checked and I can add a file but it seems like it's not saved.  

Here"'s a short recording so you can see by yourself :-)


 
![Peek 2022-11-30 16-48](https://user-images.githubusercontent.com/7746024/204844507-4b89a03b-a125-45eb-adf5-7f0ea681d836.gif)

**Comment by eusonlito** [comment]
Ok! I see... allowed file extensions are csv,doc,docx,jpg,pdf,png,odt,ods,txt,xls,xlsx,zip.

**Comment by eusonlito** [comment]
Maybe accept any extension? The files are stored encrypted on filesystem.

**Comment by eusonlito** [comment]
Removed file extension check :)

**Comment by wangee** [comment]
Hi eusonlito,

Works like a charm!  Thanks! 
Do you think it could be doable to have the fine name displayed instead of "no file chosen" ?   
Seeing "no file chosen" is quite confusing for the user.


![image](https://user-images.githubusercontent.com/7746024/205029419-11f56d32-842c-4762-b06b-16629062d285.png)

**Comment by eusonlito** [comment]
Is not possible with the default `input type="file"`. HTML does not allow to customize the text. I can try some CSS + Javascript inputs :)

**Comment by eusonlito** [comment]
Update file upload UI :)

```
git pull
```

**Comment by wangee** [comment]
Wonderful!   No doubt users will like that feature :)  Thanks!
