### ISSUE TITLE
Keepass Importer

### ISSUE THREAD

**Issue by andreacomplus** [eusonlito/Password-Manager#46]
Hello @eusonlito ,
i'm writing a Keepass XML importer as a command.
I'm not a Laravel expert , so i have some trouble persisting the entities.
For each item, i create an instance of the appropriate type.
But then, I don't know how to persist these in the DB, maybe you can give me a clue ?

```php
foreach ($validEntries as $entry) {
    $className = '\\' . $entry->type;
    /** @var TypeAbstract $entity */
    $entity       = new $className($entry->getPayload());
    
    // .. and now ?
}

// $className can be, for example, \App\Domains\App\Service\Type\Format\SSH
// $entry->getPayload() returns an array with the appropriate payload for each Type.
```

**Comment by eusonlito** [comment]
A Type Manager can be loaded as https://github.com/eusonlito/Password-Manager/blob/master/app/Domains/App/Action/CreateUpdateAbstract.php#L50

Then you can get the App data using https://github.com/eusonlito/Password-Manager/blob/master/app/Domains/App/Action/CreateUpdateAbstract.php#L56

Set Teams, tags, etc...

And finally Save: https://github.com/eusonlito/Password-Manager/blob/master/app/Domains/App/Action/Create.php

:)

**Comment by eusonlito** [comment]
Closed due to inactivity.
