### ISSUE TITLE
REQ: Hide application via flag / soft delete / trash / archive

### ISSUE THREAD

**Issue by andreacomplus** [eusonlito/Password-Manager#47]
An option to hide an Application from users is useful in enterprise context.  
This could be accomplished via a flag (Hide/Unhide), via a soft-delete/trashbin feature, or via an Archive flag.

**Comment by eusonlito** [comment]
But you can create private (no shared) apps...

**Comment by andreacomplus** [comment]
> But you can create private (no shared) apps...

Sure, but they're still visible to me, since I created that application. I want to hide it / archive it from my list as well.

**Comment by eusonlito** [comment]
And visible only inside a new "Archived" apps panel?

**Comment by andreacomplus** [comment]
I see that as a toggleable filter in the header of the Applications list, like:
- show all
- hide archived
- archived only
or as you suggest an "Archive" list, or a "Trash bin" if we want to use the trash action instead of archiving.

**Comment by eusonlito** [comment]
Ok :)

**Comment by eusonlito** [comment]
The Apps index filter will hide the archived apps by default, and the chrome extension will not return the archived apps in any case.

The filter will be:
* Active (default)
* Archived
* All

**Comment by eusonlito** [comment]
Done!
