### ISSUE TITLE
REQ: Tag improvements

### ISSUE THREAD

**Issue by andreacomplus** [eusonlito/Password-Manager#48]
- [x] Tags can be created but not deleted.  It should be possible to delete tags, eventually with a check that allows the deletion only when they're not associated to any app.
- [x] Tags list could be improved with a link to the Applications list filtered by the given tag.

**Comment by eusonlito** [comment]
Ok! I will work in this issue :)

**Comment by eusonlito** [comment]
You have the changes at `master`.

Also added more Tags tests.

Regards!
