### ISSUE TITLE
Class "Imagick" not found

### ISSUE THREAD

**Issue by Namtor-FFM** [eusonlito/Password-Manager#52]
Hello,

I have a strange issue when I create a Web Application.
Steps to reproduce:
Fill out the following fields:
- Type = Web
- Name = Test
- URL = https://github.com/
Click on Save
Actual Behavior: error message 'Class "Imagick" not found'.
Laravel Log file:
[2023-01-12 16:05:53] production.ERROR: Class "Imagick" not found {"userId":1,"exception":"[object] (Error(code: 0): Class \"Imagick\" not found at /var/www/nico/app/Domains/App/Service/Icon/Image.php:35)

Additional Information:
- Remove the URL and click Save. It works.
- Add the URL and click Save. It works too.

Is it a bug?
Thanks,
Nicolas

**Comment by eusonlito** [comment]
You need to install `php-imagick` extension.

**Comment by Namtor-FFM** [comment]
Many thanks for your help :)
