### ISSUE TITLE
Login attempts, no limit...

### ISSUE THREAD

**Issue by DomenicoParisiWeb** [eusonlito/Password-Manager#53]
I get my login password wrong 5 times, I get the "ip blocked" message, but if I try to log in immediately after with the correct password, I log in easily.
Basically it's like there's no blocking on incorrect login attempts...

**Comment by eusonlito** [comment]
The server is a local or remote?

Are you using a proxy?

IPs stored in `ip_lock` and `user_session` are the same?

**Comment by DomenicoParisiWeb** [comment]
Remote server, Plesk with nginx (inverse proxy to apache).

> IPs stored in `ip_lock` and `user_session` are the same?
Where can I see it?

**Comment by eusonlito** [comment]
The first step in login process is check if the IP is locked.

https://github.com/eusonlito/Password-Manager/blob/929313d801ba2bae567c22103aaeb335fbe9cc45/app/Domains/User/Action/AuthCredentials.php#L33

If the IP is blocked then it will throw an exception and the process will not continue with the credential verification.

Please check the IPs stored in `ip_lock` and `user_session` database tables.

Do you have the default lock and check values in `.env`:

```
# How many auth fails are allowed
AUTH_CHECK_ALLOWED=4
# Check fails in last X seconds
AUTH_CHECK_TIME=60
# Lock IP X seconds
AUTH_LOCK_TIME=60
```

**Comment by DomenicoParisiWeb** [comment]
Okay.
In "user_session" there are my login attempts, and the IP is that of the client from which I try to login (so so far so good).
Instead "ip_lock" is empty, it doesn't log the IP to lock out when failing attempts.

**Comment by eusonlito** [comment]
And no errors inside `storage/logs/laravel` folder?

The ip lock is only available using the `ip_lock` table.

**Comment by DomenicoParisiWeb** [comment]
> And no errors inside `storage/logs/laravel` folder?
No. I deleted "storage/logs/laravel-2023-01-14.log", simulated the problem again and no file is created, so no, it leaves no errors...


My env:

`[APP.....]

APP_ENV=production
APP_DEBUG=false
DEBUGBAR_ENABLED=false

DB_CONNECTION=mysql
[DB.....]
DB_LOG=false

SESSION_DRIVER=cookie
SESSION_LIFETIME=45000
SESSION_COOKIE=password-manager
SESSION_ENCRYPT=false

AUTH_CHECK_ALLOWED=5
AUTH_CHECK_TIME=60
AUTH_LOCK_TIME=60
AUTH_TFA_ENABLED=false
AUTH_CERTIFICATE_ENABLED=false
AUTH_API_SECRET_ENABLED=false

AUTH_COUNTRY_ENABLED=false
AUTH_COUNTRY_ALLOWED=
AUTH_COUNTRY_IP_WHITELIST=127.0.0.1

LOG_CHANNEL=stack
LOG_REQUEST=false
LOG_DATABASE=false
LOG_MAIL=true
LOG_CURL=false
LOG_DAYS=30

[MAIL.....]

CACHE_ENABLED=true
CACHE_DRIVER=file
CACHE_PREFIX=password-manager-cache-
CACHE_VERSION=1
CACHE_TTL=3600

SENTRY_DSN=
SENTRY_TRACES_SAMPLE_RATE=0.0`

**Comment by eusonlito** [comment]
Ok, I have tested my environment and works fine.

I will test creating a new installation using your settings.

**Comment by DomenicoParisiWeb** [comment]
If I add a line with my ip to "ip_lock", the login is blocked (great).
The problem is then that, when it reaches the bad attempts, it doesn't register the ip to exclude in the "ip_lock" table.

**Comment by eusonlito** [comment]
Ok, thanks, I understand the problem :)

Thanks!

**Comment by DomenicoParisiWeb** [comment]
I was looking here:
https://github.com/eusonlito/Password-Manager/blob/master/app/Domains/IpLock/Action/Create.php#L24

I'll wait for your directions. :)
Thanks for the support.

**Comment by eusonlito** [comment]
Solved. Was a problem with a Transaction.

I'm adding tests with this case :)
