### ISSUE TITLE
Seeder not found

### ISSUE THREAD

**Issue by CleanWeb-Dev** [eusonlito/Password-Manager#56]
When I run:
`php artisan db:seed --class=Database\\Seeders\\Database`
Return:
`Target class [Database\\Seeders\\Database] does not exist. at [...]\Password-Manager\vendor\laravel\framework\src\Illuminate\Container\Container.php:895`

I tried unsuccessfully:
`composer dump-autoload `

**Comment by eusonlito** [comment]
Are you using windows?

**Comment by DomenicoParisiWeb** [comment]
Locally Windows, remotely Linux.
Same problem...

composer.json is ok... mmmh

**Comment by eusonlito** [comment]
The `composer deploy` command works?

**Comment by DomenicoParisiWeb** [comment]
`Script sed -i 's/CACHE_VERSION=.*/CACHE_VERSION='$(head -c 16 /dev/urandom | md5sum | head -c 32)'/' .env handling the env-version event returned with error code 1
Script @composer env-version --ansi handling the deploy event returned with error code 1`

**Comment by eusonlito** [comment]
mmmm, maybe `sed` command is not available in windows...

Let me do some checks.

**Comment by eusonlito** [comment]
It's strange, I can seed without problem on all my environments.

![Screenshot from 2023-01-17 16-55-39](https://user-images.githubusercontent.com/644551/212946530-7b3822e6-acc9-4d3d-a3ec-5d11f4d65213.png)

**Comment by eusonlito** [comment]
The problem continues?
