### ISSUE TITLE
AUTH_LOCK_TIME

### ISSUE THREAD

**Issue by Namtor-FFM** [eusonlito/Password-Manager#58]
Hello,

I installed Password-Manager locally and I'm never automatically logged out (even after several days). In .env I have the default configuration AUTH_LOCK_TIME=60.
Did I forget to activate anything?
Thanks.

**Comment by eusonlito** [comment]
Session lifetime is defined as env variable `SESSION_LIFETIME` (in minutes).

https://github.com/eusonlito/Password-Manager/blob/dc0f270abe369294d8558f637f1f5da5063948d8/config/session.php#L21:L32

**Comment by eusonlito** [comment]
`AUTH_LOCK_TIME` is the time in seconds to lock an IP after `AUTH_CHECK_ALLOWED` failed login attempts.

**Comment by eusonlito** [comment]
Session time is always related to last page view (and is managed by Laravel). Also, you can set close session on tab after browser close setting true this config.

https://github.com/eusonlito/Password-Manager/blob/dc0f270abe369294d8558f637f1f5da5063948d8/config/session.php#L34

**Comment by eusonlito** [comment]
I think that the cookie sessions remains the previous value in your browser. Try to logout and login again.

What is the expiration date displayed by the browser?

![uUZg7B7jgE41Vaz4pYxx](https://user-images.githubusercontent.com/644551/214070148-1234d4b7-e06f-4cd5-9b81-3e06512831cc.png)

**Comment by Namtor-FFM** [comment]
I changed it to 1 min to better test. The Cookie password-manager has a lifetime of 1min. Although it is already expired, I can reload the page without any problem. Then the cookie is reloaded.
I don't know if it helps but I'm calling the Password Manager via the port 8080.

**Comment by eusonlito** [comment]
Ok, let me do some tests :)

**Comment by eusonlito** [comment]
I have tested the session expires in my local environment and is working fine. After 1 minute the cookie is expired and deleted by browser sending the user to the login screen.

Your cookie remains on browser after expires?

![Screenshot from 2023-01-24 11-51-08](https://user-images.githubusercontent.com/644551/214273296-ba083adc-2c3f-42f9-92dc-e6d813dfc967.png)

**Comment by Namtor-FFM** [comment]
Correct, the cookies are not deleted as you can see on this screenshot.
![image](https://user-images.githubusercontent.com/122468558/214285404-d94d5c88-87ad-45e6-b5e0-41d3fe53af42.png)

**Comment by eusonlito** [comment]
Can you try chrome. It's strange, the expired cookies must be deleted.

**Comment by Namtor-FFM** [comment]
This is Chrome. I just tried with Firefox and I have exactly the same issue: cookies are not deleted.

**Comment by eusonlito** [comment]
I have tried the change in local, stage and production and it works in all of them...

**Comment by Namtor-FFM** [comment]
When I'm thinking a bit more, this issue should come from my side because another website complains that I have too many cookies. When I remove them it is fine but just for a while.
I made some researches in the internet but couldn't find any reason why my browser does not delete expired cookies.
For Password Manager, I can restart my laptop and I'll still be logged. Pretty strange but I don't think that you can help a lot.

**Comment by eusonlito** [comment]
Ok, good luck with your research :)

**Comment by Namtor-FFM** [comment]
I think that I found something interesting regarding this issue. When I login into PasswordManager, 3 Cookies are generated:
- vAt5NjcBNQeMKGO7HxKOE8dgltLpNnGO5ltpoghd
- password-manager
- remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d
The cookie remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d has an expire date of more than a year. When I update its date like the other cookies, then PasswordManager logs out automatically as expected.
<img width="288" alt="image" src="https://github.com/eusonlito/Password-Manager/assets/122468558/f2019c9f-15b7-4f03-8f03-6b594f21fb11">
Do you think that you can do something?
