### ISSUE TITLE
Icons Delete

### ISSUE THREAD

**Issue by tunavis** [eusonlito/Password-Manager#59]
Good day,

Is is possible to delete icons, there are random icons appearing in my list?

**Comment by eusonlito** [comment]
You have an `Icons` panel on sidebar to set custom icons for each domain.

**Comment by tunavis** [comment]
Correct yes, but there are random icons being generated it does not look very pleasant, so is their a way of deleting those random onee.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by eusonlito** [comment]
Done!
