### ISSUE TITLE
App list page crashing Folder not writable 

### ISSUE THREAD

**Issue by atiqsamtia** [eusonlito/Password-Manager#6]
When I open the applications list page, this error pops up. I reset permissions for the directory but still, it isn't working. any help?

![image](https://user-images.githubusercontent.com/5112753/149844518-41015efb-bff4-4904-948c-7b16222eaa54.png)

Laravel-Packer issue maybe?

**Comment by eusonlito** [comment]
99% sure is about permissions with your project folders. Web server (or PHP daemon) and folders must have same user.

**Comment by eusonlito** [comment]
Closed due inactivity.
