### ISSUE TITLE
Web UI is not working with error code 500

### ISSUE THREAD

**Issue by devendrab** [eusonlito/Password-Manager#61]
Hello Eusonlito,

I have configured the project on CentOS 7. Also configured HTTPS using Certbot and Let's Encrypt SSL cert. 
All the code installation steps worked out well without any errors/issues. However after configuring the HTTPD, I can't seem to access the UI. I get "500 System error" message. 

HTTPD access logs has below messages -

```
52.33.193.87 - - [14/Feb/2023:04:07:24 +0000] "GET /user/auth HTTP/1.1" 500 1694
72.201.100.76 - - [14/Feb/2023:04:07:55 +0000] "GET /user/auth HTTP/1.1" 500 1694
```

I have installed the "Password-Manager" in "/var/www/html" folder. Updated the owner and group to "apache" user for entire folder and subfolders. 

```
ls -ld /var/www/html/Password-Manager/
drwxr-xr-x. 13 apache apache 4096 Feb 14 03:32 /var/www/html/Password-Manager/
```

My /etc/httpd/conf.d/pam.conf looks like below -

```
<VirtualHost *:80>
    ServerAdmin admin@mydomain.com
    DocumentRoot "/var/www/html/Password-Manager/public"
    DirectoryIndex index.php
    ServerName pam.mydomain.com
    ErrorLog "/var/log/httpd/pam.mydomain.com.error_log"
    CustomLog "/var/log/httpd/pam.mydomain.com.access_log" common
    <Directory "/var/www/html/Password-Manager/public">
        Options Indexes FollowSymLinks MultiViews
        Allowoverride All
        Order allow,deny
        allow from all
    </Directory>
RewriteEngine on
RewriteCond %{SERVER_NAME} =pam.mydomain.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerAdmin admin@mydomain.com
    DocumentRoot "/var/www/html/Password-Manager/public"
    DirectoryIndex index.php
    ServerName pam.mydomain.com
    ErrorLog "/var/log/httpd/pam.mydomain.com.error_log"
    CustomLog "/var/log/httpd/pam.mydomain.com.access_log" common
    <Directory "/var/www/html/Password-Manager/public">
        Options Indexes FollowSymLinks MultiViews
        Allowoverride All
        Order allow,deny
        allow from all
    </Directory>
SSLCertificateFile /etc/letsencrypt/live/pam.mydomain.com.cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/pam.mydomain.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateChainFile /etc/letsencrypt/live/pam.mydomain.com/chain.pem
</VirtualHost>
</IfModule>
```

I am novice with PHP LARAVEL. Any inputs/suggestions appreciated.

**Comment by eusonlito** [comment]
Check the php error log and `/var/www/html/Password-Manager/storage/logs/laravel/` folder.

**Comment by devendrab** [comment]
No logs are created. 

` ls -lth /var/www/html/Password-Manager/storage/logs/laravel/
ls: cannot access /var/www/html/Password-Manager/storage/logs/laravel/: No such file or directory`

The specific error messages on the browser are  -
`The exception occurred while attempting to log: The stream or file "/var/www/html/Password-Manager/storage/logs/laravel-2023-02-14.log" could not be opened in append mode: Failed to open stream: Permission denied
The exception occurred while attempting to log: file_put_contents(/var/www/html/Password-Manager/storage/framework/views/da39a3ee5e6b4b0d3255bfef95601890afd80709.blade.php): Failed to open stream: Permission denied (View: /var/www/html/Password-Manager/resources/views/domains/user/auth-credentials.blade.php)
Context: {"exception":{}}
Context: {"exception":{}}`

I tried changing the ownership to pass-manager user ( which I used for installation) and group to apache. Also tried changing the folder modes to 775 for "storage" folder. 

```
drwxrwxr-x. 4 pass-manager apache 87 Feb 14 02:46 logs
drwxrwxr-x. 3 pass-manager apache 38 Feb 14 02:24 app
drwxrwxr-x. 2 pass-manager apache 24 Feb 14 02:24 cache
drwxrwxr-x. 2 pass-manager apache 24 Feb 14 02:24 debugbar
drwxrwxr-x. 6 pass-manager apache 81 Feb 14 02:24 framework
drwxrwxr-x. 2 pass-manager apache 24 Feb 14 02:24 tmp
```

**Comment by devendrab** [comment]
Though I got below error message after creating first application. 

```
[DirNotWritableException](https://passman.zdatainc.io/app#trace-box-3)  [ViewException](https://passman.zdatainc.io/app#trace-box-2)  [ViewException](https://passman.zdatainc.io/app#trace-box-1)
HTTP 500 Internal Server Error
Folder /var/www/html/Password-Manager/public/storage/cache/images/0cb can not be created (View: /var/www/html/Password-Manager/resources/views/domains/app/molecules/list.blade.php) (View: /var/www/html/Password-Manager/resources/views/domains/app/molecules/list.blade.php)
```

**Comment by eusonlito** [comment]
Apache user should be able to read the project, and PHP user should be able to write in `storage` and `public/storage` folders.

**Comment by devendrab** [comment]
There is not "public/storage" folder.

**Comment by eusonlito** [comment]
Sorry, is created by code. Set the project root as PHP user.

**Comment by devendrab** [comment]
There is not separate php user on my system.

**Comment by eusonlito** [comment]
Then, you should set the project root user as same as used by PHP.

**Comment by devendrab** [comment]
Thanks, that solved the issue. I can now add the applications. Though one question with applications. 

I don't seem to be able to add any application without selection of Teams, what if credentials or passwords are private and not meant for sharing with other users?

**Comment by eusonlito** [comment]
You can create a Team called `myself` or something similar. Anyway, any app without the `Shared` checkbox it's private for the user even if he shares the team with more users.

**Comment by devendrab** [comment]
that helped, thanks.

**Comment by eusonlito** [comment]
Closing :)
