### ISSUE TITLE
Protocol mismatch behind reverse proxy

### ISSUE THREAD

**Issue by JSXRED** [eusonlito/Password-Manager#62]
There is an issue, when you run Password-Manager behind a reverse proxy.
The installation runs with the given docker-compose sample. Environment file was changed and the correct data was entered. If you now add a nginx with https in front of it, then the click on password (for copy) does not work under Main-Page "Applications" with the error message "Failed to fetch". 

![image](https://user-images.githubusercontent.com/10437799/219942595-7379138f-b076-4f37-bf22-96dee61d5fb6.png)

This is because in the property "data-copy-ajax" the protocol is http:// instead of https://. If you change this manually in the dev console it works or rewrite it with nginx sub_filter, then it also works.

**Comment by eusonlito** [comment]
Have you updated `APP_URL` in `.env` to reflect the final url?

**Comment by JSXRED** [comment]
Yes, my configuration:
`APP_URL=https://sub.tld.com/
ASSET_URL=https:/sub.tld.com`

Nginx
`location / {
		#sub_filter	'http://sub.'  'https://sub.';
		#sub_filter_once off;
		proxy_set_header      Host $host;
		proxy_set_header      X-Real-IP $remote_addr;
		proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header      X-Forwarded-Proto $scheme;
		proxy_set_header      Cookie $http_cookie;

		proxy_pass http://10.10.10.10:8080/;`

**Comment by eusonlito** [comment]
Ok, let me do some tests with same configuration :)

**Comment by eusonlito** [comment]
I have added `TrustProxies` middleware.

1. Backup the `.env` file stored inside container:
```bash
sudo docker cp passwordmanager:/var/www/passwordmanager/.env .env
```
2. Update the project code.
```bash
git pull
```
3. Copy your `.env` file inside `docker/.env`.
```bash
cp .env docker/.env
```
4. Build again the docker instance.
```bash
sudo docker-compose -f docker/docker-compose.yml build
```
6. Run the docker instance.
```bash
sudo docker-compose -f docker/docker-compose.yml up
```
7. It works?

**Comment by JSXRED** [comment]
Step: 5.
`
sudo docker cp .env passwordmanager:/var/www/passwo
rdmanager/.env
`

6. It works!

I can confirm that the issue is solved. Thank you so much for the quick support.
