### ISSUE TITLE
Cookies issue

### ISSUE THREAD

**Issue by Namtor-FFM** [eusonlito/Password-Manager#65]
Hello,

Some months ago, I told you that I had an issue with the automatic logout. Although I setup the SESSION_LIFETIME variable to 1 (sec), PasswordManager never log out automatically.
https://github.com/eusonlito/Password-Manager/issues/58

I think that I found something interesting regarding this issue. When I login into PasswordManager, 3 Cookies are generated:
- vAt5NjcBNQeMKGO7HxKOE8dgltLpNnGO5ltpoghd
- password-manager
- remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d
The cookie remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d has an expire date of more than a year. When I update its date like the other cookies, then PasswordManager logs out automatically as expected.

![image](https://github.com/eusonlito/Password-Manager/assets/122468558/ab1073bf-3cb8-4869-b84c-9b6acb6eae53)

Do you think that you can do anything here?
Many thanks.

**Comment by eusonlito** [comment]
Can you paste your `SESSION_` variables from `.env`?

**Comment by Namtor-FFM** [comment]
SESSION_DRIVER=cookie
SESSION_LIFETIME=1
SESSION_COOKIE=password-manager
SESSION_ENCRYPT=false

**Comment by eusonlito** [comment]
If you change the `SESSION_DRIVER` to `file` and redo caches with `php artisan optimize`, the result is the same?

**Comment by Namtor-FFM** [comment]
I now have only 2 cookies:
- password-manager
- remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d
But the result is the same.
