### ISSUE TITLE
APP_URL and ASSET_URL with several values

### ISSUE THREAD

**Issue by Namtor-FFM** [eusonlito/Password-Manager#66]
Hello,

In order to use PasswordManager, I either use in the URL the IP Address (http://192.168.1.4:8080/app) or the name of the Server (http://Home:8080/app).

In .env, the variables APP_URL and ASSET_URL are setup with the IP Address and PasswordManager is working correctly. When the name of the server is used, the icons are not displayed correctly. As you previously explained, this is because of these variables.

Do you know how I could add both IP Address and Server Name into these variables so that the icons are always correctly displayed?

Many thanks.

**Comment by eusonlito** [comment]
It's not possible. This variables are managed by Laravel to generate the routes and assets URLs.
