### ISSUE TITLE
Menu options are not displayed when attempting to create a new application through the standard interface, but work via direct URL.

### ISSUE THREAD

**Issue by mradom** [eusonlito/Password-Manager#67]
**Issue Description:**
When trying to create a new application with a newly created user without admin access through the standard interface, the required menu options are not displayed. However, it's noticed that creating an application directly through the URL seems to work.

**Steps to Reproduce:**

1. Log in with a newly created user without admin access.
2. Navigate to the application creation section through the standard interface.
3. Note that the menu options required for creating an application are not visible.
4. Attempt to create an application directly through the URL and check if the functionality is present.

**Attached Screenshot:**
![image](https://github.com/eusonlito/Password-Manager/assets/6789942/c9e8789c-1670-4b44-afe0-5cd3d5ca2904)

**Comment by eusonlito** [comment]
Maybe the interface can be improved, because you can click in `click aquí` to create your first app.

**Comment by mradom** [comment]
So sorry ...

**Comment by eusonlito** [comment]
:smiley: 

![image](https://github.com/eusonlito/Password-Manager/assets/644551/b20a17d1-9d4e-4f1d-9b6a-650adb39c689)
