### ISSUE TITLE
Problems with "Log"

### ISSUE THREAD

**Issue by guille-frank** [eusonlito/Password-Manager#68]
The "Log" has issues, it says it's dangerous, and even though it has an SSL certificate, it's the only part of the app where it says it's dangerous, vault.example.com/log
![image](https://github.com/eusonlito/Password-Manager/assets/103156657/25a9713a-b666-4f5a-9041-eeaedda89a4c)

**Comment by eusonlito** [comment]
The browser is Chrome?

**Comment by guillermazo** [comment]
Yeah, is Chrome

**Comment by eusonlito** [comment]
And the error is? For example, I have no problem with `/log` route:

![image](https://github.com/eusonlito/Password-Manager/assets/644551/df358476-4729-43e9-bec6-30ca1c7abf35)

Can you check the `Developer Tools` > `Console` log?
