### ISSUE TITLE
stuck on point 7

### ISSUE THREAD

**Issue by Gillus1** [eusonlito/Password-Manager#72]
I have looked everywhere but got no solution for the issue:
7.    Launch the initial migration.
php artisan migrate
-->  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it

created a new test.php with (same credentials) a select * from and that works fine.
i really would appreciate your assistance in this.

**Comment by eusonlito** [comment]
Is a database connection error. Do you have configured the .env file with the correct server ip/address?
