### ISSUE TITLE
Request for English Language Support

### ISSUE THREAD

**Issue by lifelessrasel** [eusonlito/Password-Manager#73]
First, I would like to thank you for your work on this project. It’s a fantastic tool, and I can see the effort that has gone into making it useful for so many people.

I am reaching out to kindly request the addition of English language support in the project. Adding English as a language option would open the tool to a broader global audience, allowing many more users to benefit from your work. I would be happy to assist in any way possible, whether by helping with translations, documentation, or any other support needed.

Thank you for considering this feature request. Looking forward to seeing the future developments in this project.

**Comment by eusonlito** [comment]
Change the `APP_LOCALE` `.env` config value to `en` to set english as default language :)
